In [1]:
pip install sqlalchemy pyodbc

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.50-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting pyodbc
  Downloading pyodbc-5.3.0-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.1-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\programs files\python\python312\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading sqlalchemy-2.0.50-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.1 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 5.0 MB/s eta 0:00:00
Downloading pyodbc-5.3.0-cp312-cp312-win_amd64.whl (70 kB)
Downloading greenlet-3.5.1-cp312-cp312-win_amd64.whl (238 kB)
Installing collected packages: pyodbc, greenlet, sqlalchemy

   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.1 pyodbc-5.3.0 sqlalchemy-2.0.50
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
from sqlalchemy import create_engine
import pandas as pd

# Load CSV
prod_df = pd.read_csv(
    r"D:\SQL\Supply_Chain_Mgmt\Data\products_clean.csv"
)

# SQL Server connection
engine = create_engine(
    "mssql+pyodbc://DESKTOP-S7R831B\\SQLEXPRESS/SupplychainDB?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

# Load table
prod_df.to_sql(
    "products",
    engine,
    if_exists="append",
    index=False
)

print("Loaded successfully")

ProgrammingError: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Product Card Id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Product Name'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Category Id'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Category Name'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Department Id'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Department Name'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Product Price'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Product Card Id'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Product Name'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Category Id'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Category Name'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Department Id'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Department Name'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Product Price'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
[SQL: INSERT INTO products ([Product Card Id], [Product Name], [Category Id], [Category Name], [Department Id], [Department Name], [Product Price]) VALUES (?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 2511 characters truncated ... ?, ?, ?), (?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?)]
[parameters: (1360, 'Smart watch', 73, 'Sporting Goods', 2, 'Fitness', 327.75, 365, 'Perfect Fitness Perfect Rip Deck', 17, 'Cleats', 4, 'Apparel', 59.99000168, 627, "Under Armour Girls' Toddler Spine Surge Runni", 29, 'Shop By Sport', 5, 'Golf', 39.99000168, 502, "Nike Men's Dri-FIT Victory Golf Polo", 24, "Women's Apparel", 5, 'Golf', 50.0, 278, "Under Armour Men's Compression EV SL Slide", 13, 'Electronics', 3, 'Footwear', 44.99000168, 249, "Under Armour Women's Micro G Skulpt Running S", 12, 'Boxing & MMA', 3, 'Footwear', 54.97000122, 191, "Nike Men's Free 5.0+ Running Shoe", 9, 'Cardio Equipment', 3, 'Footwear', 99.98999786, 917 ... 726 parameters truncated ... 109.9899979, 652, "Merrell Women's Grassbow Sport Waterproof Hik", 30, "Men's Golf Clubs", 6, 'Outdoors', 129.9900055, 647, "Merrell Women's Siren Mid Waterproof Hiking B", 30, "Men's Golf Clubs", 6, 'Outdoors', 134.9900055, 646, "Merrell Women's Grassbow Sport Hiking Shoe", 30, "Men's Golf Clubs", 6, 'Outdoors', 99.98999786, 1361, 'Toys', 74, 'Toys', 7, 'Fan Shop', 11.53999996, 1073, 'Pelican Sunstream 100 Kayak', 48, 'Water Sports', 7, 'Fan Shop', 199.9900055, 1059, 'Pelican Maverick 100X Kayak', 48, 'Water Sports', 7, 'Fan Shop', 349.9899902, 1014, "O'Brien Men's Neoprene Life Vest", 46, 'Indoor/Outdoor Games', 7, 'Fan Shop', 49.97999954)]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [3]:
prod_df.columns = [
    "Product_Card_Id",
    "Product_Name",
    "Category_Id",
    "Category_Name",
    "Department_Id",
    "Department_Name",
    "Product_Price"
]

In [4]:
print(prod_df.columns.tolist())

['Product_Card_Id', 'Product_Name', 'Category_Id', 'Category_Name', 'Department_Id', 'Department_Name', 'Product_Price']

In [5]:
prod_df.to_sql(
    "products",
    engine,
    if_exists="append",
    index=False
)

118

In [6]:
prod_df.head(5).to_sql(
    "products",
    engine,
    if_exists="append",
    index=False
)

5

In [12]:
import pandas as pd
ord_df = pd.read_csv(
    r"D:\SQL\Supply_Chain_Mgmt\Python_Codes\orders.csv",
    sep=";",
)
ord_df

,Order Id,order date (DateOrders),Order Status,Order City,Order State,Order Country,Order Region,Market
0,77202,1/31/2018 22:56,COMPLETE,Bekasi,Java Occidental,Indonesia,Southeast Asia,Pacific Asia
1,75939,1/13/2018 12:27,PENDING,Bikaner,Rajastán,India,South Asia,Pacific Asia
2,75938,1/13/2018 12:06,CLOSED,Bikaner,Rajastán,India,South Asia,Pacific Asia
3,75937,1/13/2018 11:45,COMPLETE,Townsville,Queensland,Australia,Oceania,Pacific Asia
4,75936,1/13/2018 11:24,PENDING_PAYMENT,Townsville,Queensland,Australia,Oceania,Pacific Asia
...,...,...,...,...,...,...,...,...
65747,26773,1/26/2016 19:25,CLOSED,Ho Chi Minh City,Ciudad Ho Chi Minh,Vietnam,Southeast Asia,Pacific Asia
65748,26463,1/22/2016 6:49,PENDING_PAYMENT,Ezhou,Hubei,China,Eastern Asia,Pacific Asia
65749,26383,1/21/2016 2:47,CLOSED,Tawau,Sabah,Malasia,Southeast Asia,Pacific Asia
65750,26327,1/20/2016 7:10,ON_HOLD,Semarang,Java Central,Indonesia,Southeast Asia,Pacific Asia
65751,26118,1/17/2016 5:56,SUSPECTED_FRAUD,Ratlam,Madhya Pradesh,India,South Asia,Pacific Asia

In [13]:
ord_df.info()
ord_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65752 entries, 0 to 65751
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Order Id                 65752 non-null  int64
 1   order date (DateOrders)  65752 non-null  object
 2   Order Status             65752 non-null  object
 3   Order City               65752 non-null  object
 4   Order State              65752 non-null  object
 5   Order Country            65752 non-null  object
 6   Order Region             65752 non-null  object
 7   Market                   65752 non-null  object
dtypes: int64(1), object(7)
memory usage: 4.0+ MB

Order Id                   0
order date (DateOrders)    0
Order Status               0
Order City                 0
Order State                0
Order Country              0
Order Region               0
Market                     0
dtype: int64

In [14]:
ord_df["order date (DateOrders)"] = pd.to_datetime(
    ord_df["order date (DateOrders)"]
)

In [15]:
ord_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65752 entries, 0 to 65751
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Order Id                 65752 non-null  int64
 1   order date (DateOrders)  65752 non-null  datetime64[ns]
 2   Order Status             65752 non-null  object
 3   Order City               65752 non-null  object
 4   Order State              65752 non-null  object
 5   Order Country            65752 non-null  object
 6   Order Region             65752 non-null  object
 7   Market                   65752 non-null  object
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 4.0+ MB

In [16]:
ord_df.columns = [
    "Order_Id",
    "Order_Date",
    "Order_Status",
    "Order_City",
    "Order_State",
    "Order_Country",
    "Order_Region",
    "Market"
]

In [17]:
print(ord_df.columns)

Index(['Order_Id', 'Order_Date', 'Order_Status', 'Order_City', 'Order_State',
       'Order_Country', 'Order_Region', 'Market'],
      dtype='object')

In [18]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://DESKTOP-S7R831B\\SQLEXPRESS/SupplychainDB?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

ord_df.to_sql(
    "orders",
    engine,
    if_exists="append",
    index=False
)

252

In [19]:
ord_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65752 entries, 0 to 65751
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_Id       65752 non-null  int64
 1   Order_Date     65752 non-null  datetime64[ns]
 2   Order_Status   65752 non-null  object
 3   Order_City     65752 non-null  object
 4   Order_State    65752 non-null  object
 5   Order_Country  65752 non-null  object
 6   Order_Region   65752 non-null  object
 7   Market         65752 non-null  object
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 4.0+ MB

In [20]:
ship_df = pd.read_csv(
    r"D:\SQL\Supply_Chain_Mgmt\Python_Codes\shipping.csv",
    sep=";"
)

In [21]:
ship_df

,Order Id,Shipping Mode,Delivery Status,Late_delivery_risk,Days for shipping (real),Days for shipment (scheduled),shipping date (DateOrders)
0,77202,Standard Class,Advance shipping,0,3,4,2/3/2018 22:56
1,75939,Standard Class,Late delivery,1,5,4,1/18/2018 12:27
2,75938,Standard Class,Shipping on time,0,4,4,1/17/2018 12:06
3,75937,Standard Class,Advance shipping,0,3,4,1/16/2018 11:45
4,75936,Standard Class,Advance shipping,0,2,4,1/15/2018 11:24
...,...,...,...,...,...,...,...
65747,26773,First Class,Late delivery,1,2,1,1/28/2016 19:25
65748,26463,Standard Class,Shipping on time,0,4,4,1/26/2016 6:49
65749,26383,Second Class,Late delivery,1,4,2,1/25/2016 2:47
65750,26327,Standard Class,Advance shipping,0,3,4,1/23/2016 7:10
65751,26118,Standard Class,Shipping canceled,0,4,4,1/21/2016 5:56

In [22]:
ship_df.info()
ship_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65752 entries, 0 to 65751
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Order Id                       65752 non-null  int64
 1   Shipping Mode                  65752 non-null  object
 2   Delivery Status                65752 non-null  object
 3   Late_delivery_risk             65752 non-null  int64
 4   Days for shipping (real)       65752 non-null  int64
 5   Days for shipment (scheduled)  65752 non-null  int64
 6   shipping date (DateOrders)     65752 non-null  object
dtypes: int64(4), object(3)
memory usage: 3.5+ MB

Order Id                         0
Shipping Mode                    0
Delivery Status                  0
Late_delivery_risk               0
Days for shipping (real)         0
Days for shipment (scheduled)    0
shipping date (DateOrders)       0
dtype: int64

In [23]:
ship_df["shipping date (DateOrders)"] = pd.to_datetime(
    ship_df["shipping date (DateOrders)"]
)

In [24]:
ship_df.columns = [
    "Order_Id",
    "Shipping_Mode",
    "Delivery_Status",
    "Late_Delivery_Risk",
    "Days_For_Shipping_Real",
    "Days_For_Shipment_Scheduled",
    "Shipping_Date"
]

In [25]:
ship_df.head()

,Order_Id,Shipping_Mode,Delivery_Status,Late_Delivery_Risk,Days_For_Shipping_Real,Days_For_Shipment_Scheduled,Shipping_Date
0,77202,Standard Class,Advance shipping,0,3,4,2018-02-03 22:56:00
1,75939,Standard Class,Late delivery,1,5,4,2018-01-18 12:27:00
2,75938,Standard Class,Shipping on time,0,4,4,2018-01-17 12:06:00
3,75937,Standard Class,Advance shipping,0,3,4,2018-01-16 11:45:00
4,75936,Standard Class,Advance shipping,0,2,4,2018-01-15 11:24:00

In [27]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://DESKTOP-S7R831B\\SQLEXPRESS/SupplychainDB?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

ship_df.to_sql(
    "shipping",
    engine,
    if_exists="append",
    index=False,
    chunksize=250,
    method="multi"
)

65752

In [29]:
sales_df = pd.read_csv(
    r"D:\SQL\Supply_Chain_Mgmt\Python_Codes\sales_fact.csv",
    sep=";"
)
sales_df

,Order Id,Customer Id,Product Card Id,Sales,Order Item Quantity,Benefit per order,Order Profit Per Order
0,77202,20755,1360,327.750000,1,91.250000,91.250000
1,75939,19492,1360,327.750000,1,-249.089996,-249.089996
2,75938,19491,1360,327.750000,1,-247.779999,-247.779999
3,75937,19490,1360,327.750000,1,22.860001,22.860001
4,75936,19489,1360,327.750000,1,134.210007,134.210007
...,...,...,...,...,...,...,...
180506,26043,1005,1004,399.980011,1,40.000000,40.000000
180507,26037,9141,1004,399.980011,1,-613.770019,-613.770019
180508,26024,291,1004,399.980011,1,141.110001,141.110001
180509,26022,2813,1004,399.980011,1,186.229996,186.229996
180510,26018,7547,1004,399.980011,1,168.949997,168.949997

In [30]:
sales_df.info()
sales_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180511 entries, 0 to 180510
Data columns (total 7 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Order Id                180511 non-null  int64
 1   Customer Id             180511 non-null  int64
 2   Product Card Id         180511 non-null  int64
 3   Sales                   180511 non-null  float64
 4   Order Item Quantity     180511 non-null  int64
 5   Benefit per order       180511 non-null  float64
 6   Order Profit Per Order  180511 non-null  float64
dtypes: float64(3), int64(4)
memory usage: 9.6 MB

Order Id                  0
Customer Id               0
Product Card Id           0
Sales                     0
Order Item Quantity       0
Benefit per order         0
Order Profit Per Order    0
dtype: int64

In [31]:
sales_df.columns = [
    "Order_Id",
    "Customer_Id",
    "Product_Card_Id",
    "Sales",
    "Order_Item_Quantity",
    "Benefit_Per_Order",
    "Order_Profit_Per_Order"
]

In [32]:
sales_df.to_sql(
    "sales_fact",
    engine,
    if_exists="append",
    index=False,
    chunksize=5000
)

7988